image: node:16

build:
    script:
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh

        - echo $SSH_KEY >> ~/.ssh/deploy.key
        - chmod 600 ~/.ssh/deploy.key

        - echo -e "\nHost deploy\n\tHostName $SSH_HOST\n\tUser $SSH_USER\n\tIdentityFile ~/.ssh/deploy.key\n\tStrictHostKeyChecking no" >> ~/.ssh/config

        - cd ~/
        - echo "$PWD"

        - cat ~/.ssh/config

        - ssh deploy 'mkdir ThisIsFromGitLab'
        - cd e2s-app
        - npm i
        - npm run build
        - ls