image: node:16

build:
    script:
        - mkdir -p /home/root/.ssh
        - chmod 700 /home/root/.ssh

        - echo $SSH_KEY >> /home/root/.ssh/deploy.SSH_KEY

        - cat >>/home/root/.ssh/config << Host deploy HostName $SSH_HOST User $SSH_USER IdentityFile /home/root/.ssh/deploy.key StrictHostKeyChecking no 

        - ssh deploy 'mkdir ThisIsFromGitLab'
        - cd e2s-app
        - npm i
        - npm run build
        - ls