image: node:16

build:
    script:
        - mkdir -p /home/root/.ssh
        - chmod 700 /home/root/.ssh

        - echo $SSH_KEY >> /home/root/.ssh/deploy.SSH_KEY

        - echo -e "\nHost deploy\n\tHostName $SSH_HOST\n\tUser $SSH_USER\n\tIdentityFile /home/root/.ssh/deploy.key\n\tStrictHostKeyChecking no" >> /home/root/.ssh/config

        - ssh deploy 'mkdir ThisIsFromGitLab'
        - cd e2s-app
        - npm i
        - npm run build
        - ls