image: node:16

build:
    script:
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh

        - echo -e "$SSH_KEY" >> ~/.ssh/deploy.key
        - chmod 600 ~/.ssh/deploy.key
        - echo -e "\nHost deploy\n\tHostName $SSH_HOST\n\tUser $SSH_USER\n\tIdentityFile ~/.ssh/deploy.key\n\tStrictHostKeyChecking no " >> ~/.ssh/config

        - cd e2s-app
        - npm i
        - npm run build

        - ssh deploy 'rm -rf ~/e2s_prod/.next; rm -f ~/e2s_prod/package.json'
        - scp -r ./.next deploy:/home/ubuntu/e2s_prod
        - scp ./package.json deploy:/home/ubuntu/e2s_prod

        - ssh deploy 'cd ~/e2s_prod; screen -S e2s_prod -X quit; npm i; screen -dmS e2s_prod npm run start'
