image: node:16

Prod Deploy:
    only:
        - main
    script:
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh

        - echo -e "$SSH_KEY" >> ~/.ssh/deploy.key
        - chmod 600 ~/.ssh/deploy.key
        - echo -e "\nHost deploy\n\tHostName $SSH_HOST\n\tUser $SSH_USER\n\tIdentityFile ~/.ssh/deploy.key\n\tStrictHostKeyChecking no " >> ~/.ssh/config

        - cd e2s-app
        - npm i --legacy-peer-deps
        - npm run build

        - ssh deploy 'rm -rf ~/e2s_prod/.next; rm -f ~/e2s_prod/package.json'
        - scp -r ./.next deploy:/home/ubuntu/e2s_prod
        - scp ./package.json deploy:/home/ubuntu/e2s_prod
        - scp ./next.config.js deploy:/home/ubuntu/e2s_dev
        - scp ./next-i18next.config.js deploy:/home/ubuntu/e2s_dev

        - ssh deploy 'cd ~/e2s_prod; screen -S e2s_prod -X quit; npm i --legacy-peer-deps; screen -dmS e2s_prod npm run start'


Dev Deploy:
    only:
        - dev
    script:
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo -e "$SSH_KEY" >> ~/.ssh/deploy.key
        - chmod 600 ~/.ssh/deploy.key
        - echo -e "\nHost deploy\n\tHostName $SSH_HOST\n\tUser $SSH_USER\n\tIdentityFile ~/.ssh/deploy.key\n\tStrictHostKeyChecking no " >> ~/.ssh/config

        - cd e2s-app
        - npm i --legacy-peer-deps
        - npm run build

        - ssh deploy 'rm -rf ~/e2s_dev/.next; rm -f ~/e2s_dev/package.json'
        - scp -r ./.next deploy:/home/ubuntu/e2s_dev
        - scp ./package.json deploy:/home/ubuntu/e2s_dev
        - scp ./next.config.js deploy:/home/ubuntu/e2s_dev
        - scp ./next-i18next.config.js deploy:/home/ubuntu/e2s_dev


        - ssh deploy 'cd ~/e2s_dev; screen -S e2s_dev -X quit; npm i; screen -dmS e2s_dev npm run start -- --port 3001'

